#!/usr/bin/env bash
# Paseo — Atomic blue/green deployment.
#
# Pulls the target image, starts the inactive slot, waits for /health/ready,
# switches Caddy upstream, drains the old slot, and removes it.
# Rolls back automatically if the new slot fails health checks.
#
# Usage:
#   ./scripts/deploy.sh                          # deploy :latest
#   ./scripts/deploy.sh ghcr.io/bas-more/paseo/paseo-daemon:v0.3.1
#   HEALTH_TIMEOUT=120 ./scripts/deploy.sh       # custom timeout
#
# Prerequisites: docker, docker compose, curl, jq

set -euo pipefail

# ── Configuration ───────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

COMPOSE_PROD="$PROJECT_ROOT/docker-compose.prod.yml"
COMPOSE_DEPLOY="$PROJECT_ROOT/docker-compose.deploy.yml"
COMPOSE_CMD="docker compose -f $COMPOSE_PROD -f $COMPOSE_DEPLOY"

IMAGE="${1:-ghcr.io/bas-more/paseo/paseo-daemon:latest}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-90}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-3}"
DRAIN_TIMEOUT="${DRAIN_TIMEOUT:-30}"
STATE_FILE="$PROJECT_ROOT/.deploy-state"

CADDY_ADMIN="http://localhost:2019"
CADDY_CONTAINER="paseo-caddy"

# ── Helpers ─────────────────────────────────────────────────
log()  { printf '[deploy] %s  %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
fail() { log "FATAL: $*"; exit 1; }

require_cmd() {
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || fail "Required command not found: $cmd"
  done
}

# Resolve which slot is currently active by inspecting running containers.
get_active_slot() {
  if [ -f "$STATE_FILE" ]; then
    cat "$STATE_FILE"
    return
  fi
  if docker ps --format '{{.Names}}' | grep -q '^paseo-blue$'; then
    echo "blue"
  elif docker ps --format '{{.Names}}' | grep -q '^paseo-green$'; then
    echo "green"
  else
    echo "none"
  fi
}

opposite_slot() {
  case "$1" in
    blue)  echo "green" ;;
    green) echo "blue"  ;;
    none)  echo "blue"  ;;
    *)     fail "Unknown slot: $1" ;;
  esac
}

container_name() { echo "paseo-$1"; }
service_name()   { echo "paseo-$1"; }
image_env()      { echo "PASEO_IMAGE_$(echo "$1" | tr '[:lower:]' '[:upper:]')"; }

# Wait for /health/ready on a container via docker exec.
wait_for_health() {
  local container="$1"
  local timeout="$2"
  local interval="${3:-$HEALTH_INTERVAL}"
  local deadline=$((SECONDS + timeout))

  log "Waiting up to ${timeout}s for $container /health/ready..."
  while [ $SECONDS -lt $deadline ]; do
    if docker exec "$container" curl -sf --max-time 5 http://localhost:6767/health/ready >/dev/null 2>&1; then
      log "$container is healthy."
      return 0
    fi
    sleep "$interval"
  done
  log "$container failed health check after ${timeout}s."
  return 1
}

# Reload Caddy to point at a new upstream via its admin API.
switch_caddy_upstream() {
  local new_upstream="$1"
  log "Switching Caddy upstream to $new_upstream:6767..."

  # Caddy admin API: reload config by restarting Caddy with the new env.
  # The ACTIVE_UPSTREAM env var is read by Caddyfile.deploy at startup.
  ACTIVE_UPSTREAM="$new_upstream" $COMPOSE_CMD up -d --no-deps caddy

  # Verify Caddy reloaded and is proxying to the new upstream.
  sleep 2
  if docker exec "$CADDY_CONTAINER" wget -qO- http://localhost:2019/config/ >/dev/null 2>&1; then
    log "Caddy config reloaded successfully."
  else
    log "WARNING: Could not verify Caddy config reload."
  fi
}

# Gracefully stop a container with connection draining.
drain_and_stop() {
  local container="$1"
  local timeout="$2"

  if ! docker ps --format '{{.Names}}' | grep -q "^${container}$"; then
    log "$container is not running, nothing to drain."
    return 0
  fi

  log "Draining $container (${timeout}s grace period)..."
  # SIGTERM triggers supervisor → worker graceful shutdown (agent drain,
  # WS close frames, HTTP server close). kill_timeout in PM2 / supervisor
  # is 30s, matching our default DRAIN_TIMEOUT.
  docker stop --time "$timeout" "$container" >/dev/null 2>&1 || true
  log "$container stopped."
}

remove_container() {
  local container="$1"
  if docker ps -a --format '{{.Names}}' | grep -q "^${container}$"; then
    log "Removing $container..."
    docker rm -f "$container" >/dev/null 2>&1 || true
  fi
}

save_state() {
  local slot="$1"
  echo "$slot" > "$STATE_FILE"
  log "Deploy state saved: active=$slot"
}

save_rollback_info() {
  local old_slot="$1"
  local old_image="$2"
  local new_slot="$3"
  local new_image="$4"

  cat > "$PROJECT_ROOT/.deploy-rollback" <<EOF
# Auto-generated by deploy.sh — used by rollback.sh
ROLLBACK_FROM_SLOT=$new_slot
ROLLBACK_FROM_IMAGE=$new_image
ROLLBACK_TO_SLOT=$old_slot
ROLLBACK_TO_IMAGE=$old_image
ROLLBACK_TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
  log "Rollback info saved to .deploy-rollback"
}

# ── Preflight checks ───────────────────────────────────────
require_cmd docker curl

# Verify compose files exist
[ -f "$COMPOSE_PROD" ]   || fail "Missing $COMPOSE_PROD"
[ -f "$COMPOSE_DEPLOY" ] || fail "Missing $COMPOSE_DEPLOY"

log "=== Paseo Atomic Deploy ==="
log "Image:   $IMAGE"
log "Timeout: ${HEALTH_TIMEOUT}s health / ${DRAIN_TIMEOUT}s drain"

# ── Step 1: Determine slots ────────────────────────────────
ACTIVE=$(get_active_slot)
INACTIVE=$(opposite_slot "$ACTIVE")

log "Active slot:   $ACTIVE"
log "Inactive slot: $INACTIVE (will receive new image)"

# Capture old image for rollback metadata.
OLD_IMAGE=""
if [ "$ACTIVE" != "none" ]; then
  OLD_IMAGE=$(docker inspect --format='{{.Config.Image}}' "$(container_name "$ACTIVE")" 2>/dev/null || echo "unknown")
fi

# ── Step 2: Pull new image ─────────────────────────────────
log "Pulling $IMAGE..."
docker pull "$IMAGE"

# ── Step 3: Start green (inactive) slot ─────────────────────
GREEN_CONTAINER=$(container_name "$INACTIVE")
GREEN_SERVICE=$(service_name "$INACTIVE")
GREEN_IMAGE_ENV=$(image_env "$INACTIVE")

log "Starting $GREEN_CONTAINER with new image..."
remove_container "$GREEN_CONTAINER"

export "${GREEN_IMAGE_ENV}=${IMAGE}"
$COMPOSE_CMD up -d --no-deps "$GREEN_SERVICE"

# ── Step 4: Health-check green ──────────────────────────────
if ! wait_for_health "$GREEN_CONTAINER" "$HEALTH_TIMEOUT"; then
  log "ROLLBACK: $GREEN_CONTAINER failed health check."
  log "Removing failed container..."
  drain_and_stop "$GREEN_CONTAINER" 10
  remove_container "$GREEN_CONTAINER"
  log "Rollback complete — $ACTIVE slot unchanged."
  exit 1
fi

# ── Step 5: Switch Caddy upstream to green ──────────────────
switch_caddy_upstream "$GREEN_CONTAINER"

# ── Step 6: Drain and remove old (blue) slot ────────────────
if [ "$ACTIVE" != "none" ]; then
  BLUE_CONTAINER=$(container_name "$ACTIVE")
  drain_and_stop "$BLUE_CONTAINER" "$DRAIN_TIMEOUT"
  remove_container "$BLUE_CONTAINER"
fi

# ── Step 7: Save state ─────────────────────────────────────
save_state "$INACTIVE"
save_rollback_info "$ACTIVE" "$OLD_IMAGE" "$INACTIVE" "$IMAGE"

# ── Step 8: Final verification ──────────────────────────────
log "Running final health check..."
if wait_for_health "$GREEN_CONTAINER" 15; then
  log "=== Deploy complete ==="
  log "Active: $GREEN_CONTAINER ($IMAGE)"
else
  log "WARNING: Post-switch health check failed. Service may be degraded."
  log "Run: ./scripts/rollback.sh to revert."
  exit 1
fi
