#!/usr/bin/env pwsh
# Paseo — Atomic blue/green deployment (Windows / Docker Desktop).
#
# Pulls the target image, starts the inactive slot, waits for /health/ready,
# switches Caddy upstream, drains the old slot, and removes it.
# Rolls back automatically if the new slot fails health checks.
#
# Usage:
#   .\scripts\deploy.ps1
#   .\scripts\deploy.ps1 -Image "ghcr.io/bas-more/paseo/paseo-daemon:v0.3.1"
#   .\scripts\deploy.ps1 -HealthTimeout 120
#
# Prerequisites: docker, docker compose, curl

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

# ── Parameters ──────────────────────────────────────────────
param(
    [string]$Image = "ghcr.io/bas-more/paseo/paseo-daemon:latest",
    [int]$HealthTimeout = 90,
    [int]$HealthInterval = 3,
    [int]$DrainTimeout = 30
)

# ── Configuration ───────────────────────────────────────────
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

$ComposeProd = Join-Path $ProjectRoot "docker-compose.prod.yml"
$ComposeDeploy = Join-Path $ProjectRoot "docker-compose.deploy.yml"
$StateFile = Join-Path $ProjectRoot ".deploy-state"
$RollbackFile = Join-Path $ProjectRoot ".deploy-rollback"

$CaddyContainer = "paseo-caddy"

# ── Helpers ─────────────────────────────────────────────────
function Write-Log {
    param([string]$Message)
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    Write-Host "[deploy] $ts  $Message"
}

function Invoke-Compose {
    param([string[]]$Arguments)
    $allArgs = @("-f", $ComposeProd, "-f", $ComposeDeploy) + $Arguments
    & docker compose @allArgs
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose failed with exit code $LASTEXITCODE"
    }
}

function Get-ActiveSlot {
    if (Test-Path $StateFile) {
        return (Get-Content $StateFile -Raw).Trim()
    }
    $running = & docker ps --format "{{.Names}}" 2>$null
    if ($running -match "^paseo-blue$") { return "blue" }
    if ($running -match "^paseo-green$") { return "green" }
    return "none"
}

function Get-OppositeSlot {
    param([string]$Slot)
    switch ($Slot) {
        "blue"  { return "green" }
        "green" { return "blue" }
        "none"  { return "blue" }
        default { throw "Unknown slot: $Slot" }
    }
}

function Get-ContainerName {
    param([string]$Slot)
    return "paseo-$Slot"
}

function Get-ServiceName {
    param([string]$Slot)
    return "paseo-$Slot"
}

function Get-ImageEnvVar {
    param([string]$Slot)
    return "PASEO_IMAGE_$($Slot.ToUpper())"
}

function Wait-ForHealth {
    param(
        [string]$Container,
        [int]$Timeout,
        [int]$Interval = $HealthInterval
    )

    Write-Log "Waiting up to ${Timeout}s for $Container /health/ready..."
    $deadline = (Get-Date).AddSeconds($Timeout)

    while ((Get-Date) -lt $deadline) {
        try {
            $result = & docker exec $Container curl -sf --max-time 5 http://localhost:6767/health/ready 2>$null
            if ($LASTEXITCODE -eq 0) {
                Write-Log "$Container is healthy."
                return $true
            }
        } catch {
            # curl not ready yet
        }
        Start-Sleep -Seconds $Interval
    }

    Write-Log "$Container failed health check after ${Timeout}s."
    return $false
}

function Switch-CaddyUpstream {
    param([string]$NewUpstream)

    Write-Log "Switching Caddy upstream to ${NewUpstream}:6767..."

    $env:ACTIVE_UPSTREAM = $NewUpstream
    Invoke-Compose @("up", "-d", "--no-deps", "caddy")

    Start-Sleep -Seconds 2
    Write-Log "Caddy config reloaded."
}

function Stop-WithDrain {
    param(
        [string]$Container,
        [int]$Timeout
    )

    $running = & docker ps --format "{{.Names}}" 2>$null
    if ($running -notcontains $Container) {
        Write-Log "$Container is not running, nothing to drain."
        return
    }

    Write-Log "Draining $Container (${Timeout}s grace period)..."
    & docker stop --time $Timeout $Container 2>$null
    Write-Log "$Container stopped."
}

function Remove-OldContainer {
    param([string]$Container)

    $all = & docker ps -a --format "{{.Names}}" 2>$null
    if ($all -contains $Container) {
        Write-Log "Removing $Container..."
        & docker rm -f $Container 2>$null | Out-Null
    }
}

function Save-State {
    param([string]$Slot)
    $Slot | Out-File -FilePath $StateFile -Encoding utf8 -NoNewline
    Write-Log "Deploy state saved: active=$Slot"
}

function Save-RollbackInfo {
    param(
        [string]$OldSlot,
        [string]$OldImage,
        [string]$NewSlot,
        [string]$NewImage
    )

    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $content = @"
# Auto-generated by deploy.ps1 — used by rollback.ps1
ROLLBACK_FROM_SLOT=$NewSlot
ROLLBACK_FROM_IMAGE=$NewImage
ROLLBACK_TO_SLOT=$OldSlot
ROLLBACK_TO_IMAGE=$OldImage
ROLLBACK_TIMESTAMP=$ts
"@
    $content | Out-File -FilePath $RollbackFile -Encoding utf8
    Write-Log "Rollback info saved to .deploy-rollback"
}

# ── Preflight checks ───────────────────────────────────────
$dockerVersion = & docker --version 2>$null
if ($LASTEXITCODE -ne 0) { throw "Docker is not installed or not running." }

if (-not (Test-Path $ComposeProd))   { throw "Missing $ComposeProd" }
if (-not (Test-Path $ComposeDeploy)) { throw "Missing $ComposeDeploy" }

Write-Log "=== Paseo Atomic Deploy ==="
Write-Log "Image:   $Image"
Write-Log "Timeout: ${HealthTimeout}s health / ${DrainTimeout}s drain"

# ── Step 1: Determine slots ────────────────────────────────
$Active = Get-ActiveSlot
$Inactive = Get-OppositeSlot -Slot $Active

Write-Log "Active slot:   $Active"
Write-Log "Inactive slot: $Inactive (will receive new image)"

$OldImage = ""
if ($Active -ne "none") {
    try {
        $OldImage = & docker inspect --format="{{.Config.Image}}" (Get-ContainerName -Slot $Active) 2>$null
    } catch {
        $OldImage = "unknown"
    }
}

# ── Step 2: Pull new image ─────────────────────────────────
Write-Log "Pulling $Image..."
& docker pull $Image
if ($LASTEXITCODE -ne 0) { throw "Failed to pull image: $Image" }

# ── Step 3: Start green (inactive) slot ─────────────────────
$GreenContainer = Get-ContainerName -Slot $Inactive
$GreenService = Get-ServiceName -Slot $Inactive
$GreenImageEnv = Get-ImageEnvVar -Slot $Inactive

Write-Log "Starting $GreenContainer with new image..."
Remove-OldContainer -Container $GreenContainer

# Set the image env var for compose
[Environment]::SetEnvironmentVariable($GreenImageEnv, $Image, "Process")

Invoke-Compose @("up", "-d", "--no-deps", $GreenService)

# ── Step 4: Health-check green ──────────────────────────────
$healthy = Wait-ForHealth -Container $GreenContainer -Timeout $HealthTimeout

if (-not $healthy) {
    Write-Log "ROLLBACK: $GreenContainer failed health check."
    Write-Log "Removing failed container..."
    Stop-WithDrain -Container $GreenContainer -Timeout 10
    Remove-OldContainer -Container $GreenContainer
    Write-Log "Rollback complete - $Active slot unchanged."
    exit 1
}

# ── Step 5: Switch Caddy upstream to green ──────────────────
Switch-CaddyUpstream -NewUpstream $GreenContainer

# ── Step 6: Drain and remove old (blue) slot ────────────────
if ($Active -ne "none") {
    $BlueContainer = Get-ContainerName -Slot $Active
    Stop-WithDrain -Container $BlueContainer -Timeout $DrainTimeout
    Remove-OldContainer -Container $BlueContainer
}

# ── Step 7: Save state ─────────────────────────────────────
Save-State -Slot $Inactive
Save-RollbackInfo -OldSlot $Active -OldImage $OldImage -NewSlot $Inactive -NewImage $Image

# ── Step 8: Final verification ──────────────────────────────
Write-Log "Running final health check..."
$finalHealthy = Wait-ForHealth -Container $GreenContainer -Timeout 15

if ($finalHealthy) {
    Write-Log "=== Deploy complete ==="
    Write-Log "Active: $GreenContainer ($Image)"
} else {
    Write-Log "WARNING: Post-switch health check failed. Service may be degraded."
    Write-Log "Run: .\scripts\rollback.ps1 to revert."
    exit 1
}
